In [58]:
# Importing required libraries
import pandas as pd
import numpy as np

In [59]:
# Loading the CSV file

df = pd.read_csv("D:\Celebal Assignments\Week1_assign\Combined_dataset.csv")

# Displaying first few rows
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [60]:
# Checking dataset shape
print("Shape of dataset:", df.shape)

# Column names
print("\nColumns:")
print(df.columns)

# Data types
print("\nData Types:")
print(df.dtypes)

Shape of dataset: (1000, 24)

Columns:
Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

Data Types:
product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [61]:
# First 5 rows
print("First 5 Records:")
display(df.head())

# Last 5 rows
print("Last 5 Records:")
display(df.tail())

First 5 Records:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

Last 5 Records:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [62]:
# Finding missing values in each column
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [69]:
# Filling missing numerical values with mean

df['discount'] = df['discount'].fillna(df['discount'].mean())

# Filling missing text values with 'Not Available'

df['seller_name'] = df['seller_name'].fillna('Not Available')
df['seller_information'] = df['seller_information'].fillna('Not Available')
df['what_customers_said'] = df['what_customers_said'].fillna('Not Available')
df['videos'] = df['videos'].fillna('Not Available')
df['variations'] = df['variations'].fillna('Not Available')

print("Missing values after cleaning:")
print(df.isnull().sum())
df

Missing values after cleaning:
product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
engagement_value          0
dtype: int64

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,engagement_value
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,59925.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,194233.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,Not Available,Not Available,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,677774.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,Not Available,Not Available,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1762100.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,Not Available,Not Available,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Not Available,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,34788.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890.0,INR,http://assets.myntassets.com/assets/images/136...,...,Not Available,Not Available,"[{""size"":""Onesize""}]","[""pi-13698258""]",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,130790.0
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,195800.0
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950.0,INR,http://assets.myntassets.com/assets/images/170...,...,Not Available,Not Available,"[{""size"":""Onesize""}]",Not Available,Not Available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,39750.0
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,Not Available,Tru███m R███il,"[{""size"":""Onesize""}]",Not Available,Sho███o. ███-10█████████enu███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,44812.0
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699.0,INR,http://assets.myntassets.com/assets/images/186...,...,Not Available,Not Available,"[{""size"":""Medium""}]",Not Available,Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,112539.0

In [70]:
print(df['final_price'].head())
print(df['final_price'].dtype)

0    3995.0
1    2899.0
2    2999.0
3    1675.0
4    2899.0
Name: final_price, dtype: float64
float64

In [71]:
# Remove quotes, currency symbol and commas

df['final_price'] = (
    df['final_price']
    .astype(str)
    .str.replace('"', '', regex=False)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
)

# Convert to numeric
df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

print(df['final_price'].head())
print(df['final_price'].dtype)

0    3995.0
1    2899.0
2    2999.0
3    1675.0
4    2899.0
Name: final_price, dtype: float64
float64

In [73]:
# Using ratings_count as a proxy metric since quantity data is unavailable
#SINCE QUANTITY COLUMN IS NOT GIVEN *************************************** 
df['engagement_value'] = df['final_price'] * df['ratings_count']

df[['final_price', 'ratings_count', 'engagement_value']]

     final_price  ratings_count  engagement_value
0         3995.0             15           59925.0
1         2899.0             67          194233.0
2         2999.0            226          677774.0
3         1675.0           1052         1762100.0
4         2899.0             12           34788.0
..           ...            ...               ...
995      11890.0             11          130790.0
996       8900.0             22          195800.0
997       7950.0              5           39750.0
998       2636.0             17           44812.0
999        699.0            161          112539.0

[1000 rows x 3 columns]

In [75]:
# Saving the cleaned dataset as a new CSV file

df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.